package ao.snakewarz.bots.search.puct

import kotlin.math.abs
import kotlin.math.exp
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * The bits matter here, not just the value.
 *
 * `portableExp` exists so that a softmax prior computes the same `Double` on the JVM and in wasm.
 * The tolerance tests below say it is an exponential; the golden-bits test says it is *this*
 * exponential — and because this suite recompiles to wasm and runs in a real browser, a golden-bits
 * assertion that passes on both targets **is** the evidence that the series is portable, rather than
 * an argument that it ought to be. That is the one claim `kotlin.math.exp` cannot make.
 *
 * `kotlin.math.exp` appears here as the oracle for the same reason `PortableLogTest` uses
 * `kotlin.math.ln`: it is the only way to check the series at all, and it is what would notice
 * somebody replacing it with the stdlib call for tidiness. SW-02 binds `:bots`' main sources.
 */
class PortableExpTest {
    @Test
    fun `agrees with the standard exponential across the range a softmax will ask for`() {
        // A stabilised softmax hands it nothing above zero, but the reduction is symmetric and a
        // one-sided test would not exercise the negative rounding of k at all.
        val samples = doubleArrayOf(
            0.0, -0.25, -1.0, -2.5, -5.0, -10.0, -30.0, -64.0, -100.0, -700.0,
            0.25, 1.0, 2.5, 5.0, 10.0, 30.0, 64.0, 100.0, 700.0,
            -0.34657359027997264, 0.34657359027997264, 0.6931471805599453,
        )

        for (sample in samples) {
            val expected = exp(sample)
            val actual = portableExp(sample)

            assertTrue(
                abs(actual - expected) <= 1e-14 * expected,
                "portableExp($sample) was $actual, exp gives $expected",
            )
        }
    }

    @Test
    fun `zero is exactly one, which is what the softmax rests on`() {
        // The best score is subtracted before exponentiating, so the largest weight is exp(0). If
        // that came back as 0.9999999999999999 the total could not be relied on to be at least one,
        // and every claim about the normalisation would be approximate instead of structural.
        assertEquals(1.0, portableExp(0.0))
        assertEquals(1.0, portableExp(-0.0))
    }

    @Test
    fun `it is monotonic, which is what a ranking actually needs of it`() {
        var previous = portableExp(-64.0)
        var step = -639
        while (step <= 639) {
            val current = portableExp(step / 10.0)
            assertTrue(current > previous, "portableExp(${step / 10.0}) did not exceed its predecessor")
            previous = current
            step++
        }
    }

    @Test
    fun `powers of two come back exact, because the scaling is a bit pattern rather than a series`() {
        // exp(k * ln2) reduces to r = 0 only if the two-part ln2 is doing its job; a single-constant
        // reduction leaves a residue here and the answer drifts by an ulp per power.
        assertEquals(2.0, portableExp(0.6931471805599453))
        assertEquals(1.0 / 2.0, portableExp(-0.6931471805599453))
    }

    @Test
    fun `an argument outside its declared range is refused rather than quietly saturating`() {
        assertFailsWith<IllegalArgumentException> { portableExp(701.0) }
        assertFailsWith<IllegalArgumentException> { portableExp(-701.0) }
    }

    @Test
    fun `the golden bits, which are what a softmax prior would rest on`() {
        // Generated by running this function, exactly like the golden move-stream hashes. This test
        // also runs in Chrome, and that is the whole point of it: identical bits on two targets is
        // the evidence that `+ - * /` was enough.
        val samples = doubleArrayOf(-0.5, -1.0, -3.0, -10.0, -64.0)

        assertEquals(
            listOf(
                4603638362051417610L, // exp -0.5 = 0.6065306597126334
                4600298746774613816L, // exp -1   = 0.36787944117144233
                4587335893757374639L, // exp -3   = 0.049787068367863944
                4541824671844433050L, // exp -10  = 4.539992976248485e-5
                4190997289430541516L, // exp -64  = 1.603810890548638e-28
            ),
            samples.map { portableExp(it).toRawBits() },
            "as doubles: ${samples.map { portableExp(it) }}",
        )
    }
}
