package ao.snakewarz.bots.search.uct

import kotlin.math.abs
import kotlin.math.ln
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * The bits matter here, not just the value.
 *
 * `portableLog` exists so UCB1 computes the same `Double` on the JVM and in wasm. The tolerance
 * tests below say it is a logarithm; the golden-bits test says it is *this* logarithm, and it is the
 * one that would notice somebody replacing the series with `kotlin.math.ln` for tidiness.
 */
class PortableLogTest {
    @Test
    fun `agrees with the standard logarithm across the range a search will ask for`() {
        // Visit counts, mostly: 1 up to a budget's worth, plus the extremes to prove the exponent
        // decomposition works away from 1.
        val samples = doubleArrayOf(
            1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 10.0, 64.0, 100.0, 1_000.0, 10_000.0, 1_000_000.0,
            0.5, 0.1, 1e-8, 1e-300, 1e300, 1.4142135623730951, 0.7071067811865476,
        )

        for (sample in samples) {
            val expected = ln(sample)
            val actual = portableLog(sample)
            val tolerance = 1e-13 * (abs(expected) + 1.0)

            assertTrue(
                abs(actual - expected) <= tolerance,
                "portableLog($sample) was $actual, ln gives $expected",
            )
        }
    }

    @Test
    fun `the anchors are exact`() {
        // ln(1) is the one value a series like this can get wrong by an ulp and nobody would notice,
        // so pin it: s is exactly zero there, and the whole polynomial must fall away.
        assertEquals(0.0, portableLog(1.0))
        assertEquals(0.6931471805599453, portableLog(2.0), "ln 2 is the constant the decomposition rests on")
    }

    @Test
    fun `it is monotonic, which is all UCB1 actually needs of it`() {
        var previous = portableLog(1.0)
        for (visits in 2..20_000) {
            val current = portableLog(visits.toDouble())
            assertTrue(current > previous, "portableLog($visits) did not exceed portableLog(${visits - 1})")
            previous = current
        }
    }

    @Test
    fun `subnormals decompose too, rather than returning nonsense`() {
        // Not a value UCB1 will ever pass it, but the branch exists and an untested branch is a
        // liability. 4.9e-324 is the smallest positive Double.
        val smallest = Double.fromBits(1L)
        assertTrue(abs(portableLog(smallest) - ln(smallest)) <= 1e-10, "portableLog($smallest)")
    }

    @Test
    fun `a non-positive argument is refused rather than quietly returning NaN`() {
        assertFailsWith<IllegalArgumentException> { portableLog(0.0) }
        assertFailsWith<IllegalArgumentException> { portableLog(-1.0) }
    }

    @Test
    fun `the golden bits, which are what the move-stream hashes rest on`() {
        // Generated by running this function, exactly like the golden move-stream hashes. A failure
        // here is a question -- did the series change on purpose? -- and never automatically a bug.
        val samples = doubleArrayOf(2.0, 3.0, 10.0, 64.0, 10_000.0)

        assertEquals(
            listOf(
                4604418534313441775L, // ln 2      = 0.6931471805599453
                4607626529066517258L, // ln 3      = 1.0986122886681096
                4612367379483415829L, // ln 10     = 2.3025850929940455
                4616368504503511923L, // ln 64     = 4.1588830833596715
                4621374578738156821L, // ln 10_000 = 9.210340371976182
            ),
            samples.map { portableLog(it).toRawBits() },
            "as doubles: ${samples.map { portableLog(it) }}",
        )
    }
}
